version: '3.1'

services:
  web:
    depends_on:
      - api
    build: ./web/.
    restart: always
    ports:
      - 80:80

  api:
    depends_on:
      - database
    build: ./api/.
    restart: always
    environment:
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_DB: "${DATABASE_DB}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      AWS_KEY: "${AWS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      AWS_S3_BUCKET: "${AWS_S3_BUCKET}"

  database:
    build: ./database/.
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_DB}"

