version: '3.1'

services:

  api:
    depends_on:
      - database
    build: ./api/.
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_USER: "${POSTGRES_USER}"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_DB: "${POSTGRES_DB}"
      DATABASE_HOST: "${POSTGRES_HOST}"
      DATABASE_PORT: "${POSTGRES_PORT}"
      AWS_KEY: "${AWS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      AWS_S3_BUCKET: "${AWS_S3_BUCKET}"

  database:
    build: ./database/.
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
