CREATE TABLE IF NOT EXISTS "public"."file_metadata" (
 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "created_at" TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp,
 "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp,
 "hash" TEXT NOT NULL,
 "file_name" TEXT NOT NULL,
 "file_size" TEXT NOT NULL,
 "file_location" TEXT NOT NULL,
 UNIQUE("hash")
);

CREATE TABLE IF NOT EXISTS "public"."file_duplicate_event" (
 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "created_at" TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp,
 "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp,
 "file_metadata_id" INTEGER NOT NULL,
 FOREIGN KEY ("file_metadata_id") REFERENCES "public"."file_metadata" ("id")
);
